### ISSUE TITLE
"tpm returned 126" on source of `tmux.conf`

### ISSUE THREAD

**Issue by erikw** [hallazzang/tmux-reset#3]
This is exactly the plugin that I've been needing for long time! Sometimes weird settings get set somehow during an active session and to be able to resource my `tmux.conf` to reset everything is just what I need, instead of killing the whole session and restart.

However when I source my `tmux.conf` I get

```
'~/.config/tmux/plugins/tpm/tpm' returned 126
```

This is my setup in `tmux.conf`:
```
# Top of the file
source ~/.config/tmux/plugins/tmux-reset/tmux-reset

[..]
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'hallazzang/tmux-reset'

run-shell '~/.config/tmux/plugins/tpm/tpm'
```

The settings are all reseted, but I wonder where this error `126` comes from.

Have I configured the plugin correctly?

Thanks for the plugin!

**Comment by hallazzang** [comment]
Hi, sorry for the late reply. It seems the problem is related to tpm itself. Can you check your tmux&tpm version?

**Comment by erikw** [comment]
```console
$ tmux -V
tmux 3.2a
$ cd ~/.config/tmux/plugins/tpm 
$ git rev-parse HEAD
693e5a2a0f6acfd2666882655d5dfd32e8c6c50b
```

Strangely I don't see this behavior anymore! I think we can close this for now.

(I did a `git pull` in the tpm repo now as well, after first testing again)

**Comment by sdondley** [comment]
I'm seeing this problem. 

tmux next-3.5
tpm commit: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946

tpm was not giving me problems prior to installing this plugin
